### ISSUE TITLE
Support for markdown output for MKDocs

### ISSUE THREAD

**Issue by agarthetiger** [xlab-steampunk/ansible-doc-extractor#5]
Hi. I stumbled across this from the https://steampunk.si/posts/documenting-ansible-collections/ blog post and this is (almost) exactly what I was looking for!

I am writing an Ansible Collection and want to put the Collection's module documentation on GitHub pages. Generating the docs from what we already have to write in the module source is perfect. I actually enjoy writing useful documentation but even I baulk at having to write it and maintain it in more than once place.

I would like to use this project to generate markdown output though, as I really like MKDocs and it's search functionality which wirks with GitHub Pages. I see that I can use a custom template and output markdown but the resulting file is still named .rst even if I call my template module.md.j2 

Before I dive in to the code and raise a PR, would this be something you'd be interested in incorporating?

**Comment by tadeboro** [comment]
Hi @agarthetiger.

Adding proper support for different output formats is definitely something that we are interested in.

Since we are currently deep in the pre-alpha stage of development and breaking the backward compatibility is not much of a problem, maybe we can transform the CLI interface into something that is output-agnostic? For example, into something like:

    $ ansible-doc-extractor --template temp.md.j2 module/path.py output/path.md

where `module/path.py` is our Ansible module that we wish to extract documentation from, and the `temp.md.j2` is a template that the extractor will use to render the `output/path.md`.

As for the markdown support, we will need to add at least the `md_ify` filter that does what the [rst_ify](https://github.com/xlab-si/ansible-doc-extractor/blob/10c8689aeb140dab0d0aac908b3a747a0340bbb0/src/ansible_doc_extractor/cli.py#L29) filter does for reStructuredText.

Thanks for getting in touch and for offering your help. It is much appreciated.

**Comment by agarthetiger** [comment]
I'm glad to hear you're keen to add support for md too. There's benefits for everyone to get things incorporated upstream wherever possible. I hope I can help.

I don't think the changes need to be breaking. What I had in mind was to use the middle of the template name for the output file extension. module.rst.j2 would output files ending .rst, module.md.j2 would output files ending .md etc. I'd like to not lose the ability to generate documentation using module/*.py rather than have to generate one doc at a time. 

I'd still expect to be able to run this after we add support for markdown.

`$ ansible-doc-extractor --template module.md.j2 module/*.py`

I've started to have a go at this today, I'll raise a PR which might make things clearer although it's definitely not ready to be merged. You're right about needing an md_ify, I've started on this and it's in the PR but not finished yet. 

I wanted to let you see what I was thinking because I've got about 15 years development expereince which until about 9 months ago was C# and Java, so my Python is often not very pythonic. Please feel free to be really picky about anything and everything, I value all feedback as opportunities for me to learn quickly :)

**Comment by juremedvesek** [comment]
Merged and available in  version v0.1.8.
https://pypi.org/project/ansible-doc-extractor/
